---
version: v1
CSP: AWS
pricing-model:
  monthly-budget: 2000.0
  price-unit: Hour
scaling-horizon:
  start-time: 2018-09-01T07:00:00.1Z
  end-time: 2018-09-02T06:59:59.1Z
forecasting-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
scheduler-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
preferred-algorithm: naive
policy-settings:
  underprovisioning-allowed : false
  hetereogeneos-cluster-enabled: true
  threshold-delta-increase: 25
  max_underprovision_allowed: 50





