---
version: v1
CSP: AWS
pricing-model:
  monthly-budget: 2000
  billing-unit: hour
scaling-horizon:
  start-time: 2018-09-02T07:00:00.1Z
  endt-ime: 2018-09-03T07:00:10.1Z
forecasting-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
scheduler-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
preferred-algorithm: all
policy-settings:
  scaling-method: horizontal
  hetereogeneos-vms-allowed: true
  underprovisioning-allowed : false
  max-percentage-underprovision: 20
  pods-resize-allowed: true





