---
version: v1
service-name: movieapp
service-type: web
CSP: AWS
pricing-model:
  monthly-budget: 2000
  billing-unit: second
scaling-horizon:
  start-time: 2018-08-08T07:00:00.1Z
  end-time: 2018-08-12T07:00:00.1Z
forecasting-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
scheduler-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
preferred-algorithm: naive
policy-settings:
  scaling-method: horizontal
  heterogeneous-vms-allowed: true
  underprovisioning-allowed: false
  pods-resize-allowed: false
  vm-family: all




