forecasting-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
scheduler-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
scaling-horizon:
  start-time: 2001-12-15T02:59:43.1Z
  end-time: 2001-12-15T02:59:43.1Z
preferred-algorithm: naive-types
policy-settings:
  horizontal-enabled: true
  vertical-enabled: false
  underprovisioning-enabled : false
  hetereogeneos-cluster-enabled: true
monthly-budget: 2000.0


