app-name: movieapp
main-service-name: movieapp
app-type: dbaccess
host: http://35.225.174.194:8083
CSP: AWS
region: us-east-2
pricing-model:
  monthly-budget: 12000
  billing-unit: s
scaling-horizon:
  start-time: 2018-11-01T07:00:00Z
  end-time: 2018-11-03T06:00:00Z
forecasting-component:
  granularity: h
  #endpoint: http://7449253b.ngrok.io
  endpoint: http://172.29.39.209:8081
performance-profiles-component:
  #endpoint: http://141.40.254.24:8082
  endpoint: http://terminus.dyndns.lrz.de:8082
scheduler-component:
  #endpoint: http://172.29.39.209:8081
  endpoint: http://172.29.39.209:5555
preferred-algorithm: all
pulling-interval: 60
storage-interval: 1M
policy-settings:
  vm-scaling-method: horizontal






