---
version: v1
service-name: primeapp
service-type: compute
CSP: AWS
pricing-model:
  monthly-budget: 12000
  billing-unit: hour
scaling-horizon:
  start-time: 2018-08-25T00:00:00.000Z
  end-time: 2018-08-31T07:00:00.1Z
forecasting-component:
  endpoint: http://172.29.39.209:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://172.29.39.209:8081
  username:
  password:
  api-key:
scheduler-component:
  endpoint: http://172.29.39.209:8081
  username:
  password:
  api-key:
preferred-algorithm: naive
policy-settings:
  scaling-method: horizontal
  heterogeneous-vms-allowed: true
  underprovisioning-allowed: false
  percentage-max-underprovision: 20
  pods-resize-allowed: true
  vm-family: all




