forecasting-component:
  endpoint: http://localhost:8081
  username:
  password:
  api-key:
performance-profiles-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
scheduler-component:
  endpoint: http://localhost:8081
  user-name:
  password:
  api-key:
scaling-horizon:
  start-time: 2001-12-15T02:59:43.1Z
  end-time: 2001-12-15T02:59:43.1Z
preferred-algorithm: naive
policy-settings:
  underprovisioning-allowed : false
  hetereogeneos-cluster-allowed: true
  threshold-delta-increase: 25
  max_underprovision_allowed: 50
monthly-budget: 2000.0
CSP: AWS
app-deployed: true
price-unit: Hour


