version: '2'
services:
    spdt:
        build: .
        container_name: 'spdt'
        ports:
            - 8083:8083
        environment:
          - PROFILESDB_USER=spdt
          - PROFILESDB_PASS=spdt
          - PROFILESDB_HOST=profilesdb
          - POLICIESDB_USER=spdt
          - POLICIESDB_PASS=spdt
          - POLICIESDB_HOST=policiesdb
          - FORECASTDB_USER=spdt
          - FORECASTDB_PASS=spdt
          - FORECASTDB_HOST=forecastdb
        depends_on:
            - 'profilesdb'
            - 'policiesdb'
            - 'forecastdb'
            - 'serie-processing'
        links:
            - 'profilesdb'
            - 'policiesdb'
            - 'forecastdb'
            - 'serie-processing'


    serie-processing:
          build: Time-Serie-Processing
          container_name: 'serie'
          ports:
             - 5003:5003

    profilesdb:
         image: mongo:latest
         container_name: 'profilesdb'
         environment:
             - MONGO_DATA_DIR=/data/db
             - MONGO_LOG_DIR=/dev/null
             - MONGO_INITDB_ROOT_USERNAME=spdt
             - MONGO_INITDB_ROOT_PASSWORD=spdt

         ports:
              - 27016:27017
         volumes:
              - db-data-pro:/root/mongodb/data

    policiesdb:
         image: mongo:latest
         container_name: 'policiesdb'
         restart: always
         environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGO_INITDB_ROOT_USERNAME=spdt
            - MONGO_INITDB_ROOT_PASSWORD=spdt

         ports:
            - 27018:27017
         volumes:
            - db-data-pol:/root/mongodb/data

    forecastdb:
        image: mongo:latest
        container_name: 'forecastdb'
        restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_ROOT_USERNAME=spdt
          - MONGO_INITDB_ROOT_PASSWORD=spdt

        ports:
          - 27019:27017
        volumes:
          - db-data-for:/root/mongodb/data
volumes:
    db-data-pro:
    db-data-pol:
    db-data-for:
